FROM mcr.microsoft.com/devcontainers/base:bookworm

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America/New_York

# Username and password for the non-root user in the container.
# If these are changed then it is also necessary to change directory
# names in the panel.bash and panel.desktop files.
ARG USERNAME=student
ARG PASSWD=student
